name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-browser
        rfbrowser init
    
    - name: Run Robot Framework tests
      run: |
        robot -d results tests/
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: robot-test-results
        path: |
          results/
          screenshots/